name: Outdated PR Check

on:
  workflow_dispatch:

jobs:
  check:
    name: Outdated PR Check
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - run: npm i
     - name: Run
       run: node --no-warnings --no-deprecation --experimental-specifier-resolution=node --loader ts-node/esm scripts/outdated-pr-check.ts
       env:
        GITHUB_USER: '${{ secrets.USER }}'
        GITHUB_TOKEN: '${{ secrets.TOKEN }}'
    
